name: Provider update
description: There is an error/outdated provider information in the examples?
title: "[provider] <description>"
labels: ["provider code"]
assignees: 1ucian0

body:
- type: dropdown
  id: where
  attributes:
    label: "Where is the code that needs update?"
options:
      - Install instruction
      - qiskit.org - Transpile
      - qiskit.org - Sample a Bell State
      - qiskit.org - Run VQE
      - qiskit.org/providers/
      - Other (include where in the next field)
  validations:
      required: true

